import { resolve } from 'node:path'
import type { PagesByModule, ResolvedIguirOptions } from './types'
import { VIRTUAL_ISLANDS_ID, VIRTUAL_PAGES_PREFIX } from './types'

/**
 * Render the JS source for `virtual:iguir-pages/<module>`. The manifest
 * imports each page file lazily, so Vite emits one chunk per page.
 *
 *   export const pages = {
 *     'index':       () => import('/abs/path/pages/index.tsx'),
 *     'posts/[id]':  () => import('/abs/path/pages/posts/[id].tsx'),
 *   }
 *
 * The runtime's `mountPages()` accepts lazy entries that return either a
 * `PageEntry` or `{ default: PageEntry }`, so the page file can `export const`
 * the entry by name (`export const component = ...`) or `export default`.
 */
export function renderPagesManifest(
    moduleName: string,
    pages: PagesByModule,
): string {
    const entries = pages.get(moduleName) ?? []
    if (entries.length === 0) {
        return `export const pages = {};\nexport default pages;\n`
    }
    const lines = entries.map((p) => {
        const importPath = toPosix(p.absolutePath)
        return `    ${JSON.stringify(p.routeKey)}: () => __iguirEntry(import(${JSON.stringify(importPath)})),`
    })
    return [
        `// Generated by @iguir/vite-plugin — do not edit.`,
        ``,
        `function __iguirEntry(promise) {`,
        `    return promise.then((mod) => {`,
        `        if (mod && typeof mod === 'object' && 'default' in mod && mod.default) {`,
        `            const def = mod.default;`,
        `            if (typeof def === 'object' && 'component' in def) return def;`,
        `        }`,
        `        return {`,
        `            component: mod.default ?? mod.component,`,
        `            loader: mod.loader,`,
        `            meta: mod.meta,`,
        `            layout: mod.layout,`,
        `        };`,
        `    });`,
        `}`,
        ``,
        `export const pages = {`,
        ...lines,
        `};`,
        `export default pages;`,
        ``,
    ].join('\n')
}

/**
 * Render the JS source for `virtual:iguir-islands`. This is the client-side
 * entry that hydrates every `<iguir-island>` placeholder using `hono/jsx/dom`.
 * It eagerly imports every discovered page file because islands are declared
 * at module-eval time — that's how `defineIsland(...)` populates the registry.
 */
export function renderIslandsClient(pages: PagesByModule): string {
    const allPages: string[] = []
    for (const entries of pages.values()) {
        for (const p of entries) allPages.push(toPosix(p.absolutePath))
    }

    if (allPages.length === 0) {
        return [
            `// Generated by @iguir/vite-plugin — no pages discovered, nothing to hydrate.`,
            `export {};`,
            ``,
        ].join('\n')
    }

    const imports = allPages.map((p) => `import(${JSON.stringify(p)})`).join(',\n    ')

    return [
        `// Generated by @iguir/vite-plugin — client-side islands entry.`,
        `import { getDeclaredIslands } from '@iguir/core/jsx';`,
        `import { render } from 'hono/jsx/dom';`,
        ``,
        `async function boot() {`,
        `    // Importing every page eagerly registers every defineIsland(...) call.`,
        `    await Promise.all([`,
        `    ${imports},`,
        `    ]);`,
        `    const islands = new Map(getDeclaredIslands().map((i) => [i.name, i.component]));`,
        `    for (const el of document.querySelectorAll('iguir-island')) {`,
        `        const name = el.getAttribute('data-name');`,
        `        const propsRaw = el.getAttribute('data-props') ?? '{}';`,
        `        const Component = name ? islands.get(name) : undefined;`,
        `        if (!Component) continue;`,
        `        let props = {};`,
        `        try { props = JSON.parse(propsRaw); } catch {}`,
        `        // hono/jsx/dom's render replaces the element's children with hydrated output.`,
        `        el.innerHTML = '';`,
        `        render(Component(props), el);`,
        `    }`,
        `}`,
        ``,
        `if (document.readyState === 'loading') {`,
        `    document.addEventListener('DOMContentLoaded', boot);`,
        `} else {`,
        `    void boot();`,
        `}`,
        ``,
    ].join('\n')
}

/** Helper: is this an iguir virtual id? Used by `resolveId`. */
export function isVirtualId(id: string): boolean {
    return id === VIRTUAL_ISLANDS_ID || id.startsWith(VIRTUAL_PAGES_PREFIX)
}

/** Extract the module name from a virtual:iguir-pages/<name> id. */
export function moduleFromVirtualId(id: string): string | null {
    if (!id.startsWith(VIRTUAL_PAGES_PREFIX)) return null
    return id.slice(VIRTUAL_PAGES_PREFIX.length)
}

/** POSIX-style absolute path — Vite + ESM imports want forward slashes. */
function toPosix(path: string): string {
    return resolve(path).replace(/\\/g, '/')
}
