import type { Context, MiddlewareHandler } from 'hono'
import { anonymousChecker, createChecker, type Checker } from './resolve'
import type { AclRegistry } from './registry'
import type { AclSubject } from './types'

/**
 * Minimum shape every authenticated user must satisfy for ACL resolution.
 * The first-party `@iguir/auth` module (and any custom auth) is free to augment
 * this interface via declaration merging to add fields like `email` etc.
 *
 * `id` is optional at the ACL layer — `aclContext` only needs `roles` — but
 * auth modules will always set it, and `/me`-style endpoints rely on it.
 */
export interface AclUser extends AclSubject {
    id?: string
}

/**
 * Hono Context variables added by the ACL layer.
 * Augmented onto `ContextVariableMap` so `c.var.can` / `c.var.user` are typed
 * everywhere in a project that imports `@iguir/core`.
 */
export interface AclVariables {
    /**
     * Per-request authorization checker. Always present once `aclContext` has
     * run — `anonymousChecker()` is attached for unauthenticated requests.
     */
    can: Checker
    /** Authenticated user, populated by an upstream auth middleware. */
    user?: AclUser
}

declare module 'hono' {
    interface ContextVariableMap extends AclVariables {}
}

/** Options for the global ACL context middleware. */
export interface AclContextOptions {
    /** The compiled, frozen ACL registry built once at bootstrap. */
    registry: AclRegistry
    /**
     * How to read the authenticated user from the context. Defaults to
     * `c.get('user')`, which is what the bundled auth middleware sets.
     */
    getUser?: (c: Context) => AclUser | undefined
}

/**
 * Global middleware. Attaches `c.var.can` to every request and must be
 * installed AFTER any auth middleware that populates `c.var.user`, so the
 * checker is built against the authenticated subject.
 *
 *   app.use('*', authMiddleware())
 *   app.use('*', aclContext({ registry }))
 *
 * The registry is captured by closure — no global state is touched.
 */
export function aclContext(opts: AclContextOptions): MiddlewareHandler {
    const { registry } = opts
    const getUser = opts.getUser ?? ((c) => c.get('user') as AclUser | undefined)

    return async (c, next) => {
        const user = getUser(c)
        const checker = user ? createChecker(user, registry) : anonymousChecker()
        c.set('can', checker)
        await next()
    }
}

/** Per-route guard options. Consumed by `defineRoutes` and friends. */
export interface RequirePermissionOptions {
    /** When `false` or omitted, the guard is a no-op (public route). */
    auth?: boolean
    /** A permission declared via `defineAcl` (e.g. `'posts.update'`). */
    permission?: string
    /** Resource-level check; runs only after the permission check passes. */
    condition?: (c: Context) => boolean | Promise<boolean>
}

type ForbiddenBody = {
    error: {
        code: 'forbidden'
        message: string
        permission?: string
    }
}

const UNAUTHORIZED_BODY = {
    error: {
        code: 'unauthorized',
        message: 'Authentication required.',
    },
} as const

const FORBIDDEN_MESSAGE = 'You do not have permission to perform this action.'

/**
 * Per-route ACL guard. Generated by `defineRoutes` from each route's options.
 *
 * Behavior:
 *   - `auth !== true`  → no-op (public route, returns `next()` immediately).
 *   - no `c.var.user`  → 401 `{ error: { code: 'unauthorized', ... } }`.
 *   - permission fails → 403 `{ error: { code: 'forbidden', permission, ... } }`.
 *   - condition false  → 403 `{ error: { code: 'forbidden', ... } }`.
 *
 * Always reads `c.var.can` (set by `aclContext`) — never touches a global
 * registry, so the same factory is safe to reuse across multiple Hono apps.
 */
export function requirePermission(
    options: RequirePermissionOptions = {},
): MiddlewareHandler {
    const { auth, permission, condition } = options

    if (!auth) {
        return async (_c, next) => {
            await next()
        }
    }

    return async (c, next) => {
        if (!c.get('user')) {
            return c.json(UNAUTHORIZED_BODY, 401)
        }

        if (permission) {
            const can = c.get('can')
            if (!can || !can(permission)) {
                const body: ForbiddenBody = {
                    error: {
                        code: 'forbidden',
                        message: FORBIDDEN_MESSAGE,
                        permission,
                    },
                }
                return c.json(body, 403)
            }
        }

        if (condition) {
            const ok = await condition(c)
            if (!ok) {
                const body: ForbiddenBody = {
                    error: { code: 'forbidden', message: FORBIDDEN_MESSAGE },
                }
                return c.json(body, 403)
            }
        }

        await next()
    }
}
